apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctc-rag.fullname" . }}-config
  labels:
    {{- include "ctc-rag.labels" . | nindent 4 }}
data:
  # Chat API
  NEXT_PUBLIC_APP_ID: {{ .Values.config.appId | quote }}
  NEXT_PUBLIC_APP_KEY: {{ .Values.config.appKey | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.config.apiUrl | quote }}
  # Knowledge API
  NEXT_PUBLIC_KNOWLEDGE_API_KEY: {{ .Values.config.knowledgeApiKey | quote }}
  NEXT_PUBLIC_KNOWLEDGE_BASE_ID: {{ .Values.config.knowledgeBaseId | quote }}
  {{- if .Values.config.knowledgeApiUrl }}
  NEXT_PUBLIC_KNOWLEDGE_API_URL: {{ .Values.config.knowledgeApiUrl | quote }}
  {{- end }}
